/* MTI_DPI */

/*
 * Copyright 2002-2022 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPI_TYPES
#define INCLUDED_DPI_TYPES

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
cosim_ipc_barrier(
    int cid);

DPI_LINK_DECL DPI_DLLESPEC
int
cosim_ipc_close(
    int cid);

DPI_LINK_DECL DPI_DLLESPEC
int
cosim_ipc_get(
    int cid,
    int* pkt_cmd,
    int* pkt_size,
    int* pkt_length,
    int* pkt_ack,
    int* pkt_attr,
    int* pkt_trans_id,
    int* pkt_addr,
    const svOpenArrayHandle pkt_data);

DPI_LINK_DECL DPI_DLLESPEC
int
cosim_ipc_open(
    int cid);

DPI_LINK_DECL DPI_DLLESPEC
int
cosim_ipc_put(
    int cid,
    int pkt_cmd,
    int pkt_size,
    int pkt_length,
    int pkt_ack,
    int pkt_attr,
    int pkt_trans_id,
    int pkt_addr,
    const svOpenArrayHandle pkt_data);

DPI_LINK_DECL DPI_DLLESPEC
int
cosim_ipc_rcv(
    int cid,
    int* bnum,
    const svOpenArrayHandle pkt_data);

DPI_LINK_DECL DPI_DLLESPEC
int
cosim_ipc_set_verbose(
    int level);

DPI_LINK_DECL DPI_DLLESPEC
int
cosim_ipc_snd(
    int cid,
    int bnum,
    const svOpenArrayHandle pkt_data);

#endif 
